services:
  lms-app:
    build:
      context: .
      dockerfile: Dockerfile
      # ĐÃ XÓA target: build để lấy image Stage 2 (150MB) thay vì Stage 1 (1.4GB)
    container_name: lms-springboot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    # ĐÃ XÓA entrypoint ở đây để tránh ghi đè sai đường dẫn hoặc gây lỗi /bin/sh
    networks:
      - lms-network
    volumes:
      - app_logs:/app/logs

networks:
  lms-network:
    driver: bridge

volumes:
  app_logs:
    driver: local